### ISSUE TITLE
[BUG] pluginconfigurator does NOT appear

### ISSUE THREAD

**Issue by PaulGuyNitro1** [eternalUnion/UKPluginConfigurator#10]
### Description
(this was after patch 15d from the Full Arsenal Update)

### Reproduction
how am i supposed to know how to reproduct shit

### Installed plugins
- Plugin Configurator
- Angry Level Loader

### Extra
![image](https://github.com/eternalUnion/UKPluginConfigurator/assets/170478251/6e9e3058-9c5e-4a08-b583-93b624391de2)

**Comment by PaulGuyNitro1** [comment]
please help, i am waiting

**Comment by eternalUnion** [comment]
Could be a problem with the release. For now, [revert to 1.9.0](https://github.com/eternalUnion/UKPluginConfigurator/releases/tag/1.9.0) until I detect the problem.

**Comment by PaulGuyNitro1** [comment]
revert to 1.9.0? alright
