### ISSUE TITLE
[BUG] Presets is incorrectly spelled in the Plugin Configurator section of the... Config

### ISSUE THREAD

**Issue by UntotenTheo** [eternalUnion/UKPluginConfigurator#5]
### Description
Presests, should be Presets

### Reproduction
Options > Plugin Config > Plugin Configurator > Configure > Look up > "Presests"

### Installed plugins
- Plugin Configurator
- ultrapain, angry, style editor although all of these are irrelevant

### Extra
![image](https://github.com/eternalUnion/UKPluginConfigurator/assets/75056493/5320e7da-7ca9-4519-98f8-287d07d069f3)

**Comment by eternalUnion** [comment]
Since it is a visual bug will release it with the next update but will not make a specific one for this alone

**Comment by UntotenTheo** [comment]
fair enoug
