### ISSUE TITLE
[QUESTION] Why is there a stripped ULTRAKILL DLL?

### ISSUE THREAD

**Issue by averyocean65** [eternalUnion/UKPluginConfigurator#8]
While browsing through this plugin's repository, I noticed that `PluginConfigurator/Libs` contains `Assembly-CSharp.dll`.
Thankfully, after some investigation it appears that the function implementations have been removed, but I want to ask, why did you guys upload these DLLs when you could just reference them from your ULTRAKILL directory?

**Comment by eternalUnion** [comment]
Not all users have ultrakill installed at the same directory. Having stripped dll ensures that the project will compile on all setups. Also dll could change between game versions.

**Comment by eternalUnion** [comment]
Also the dll is not publicized in game. It will fail to compile with the game dll

**Comment by averyocean65** [comment]
Could you please elaborate on "publicized in game"?

**Comment by eternalUnion** [comment]
Publicized dll means all methods and fields are public, so you can access internal members of the class without reflection. If you reference the original dll you will get errors from trying to access members outside of the class.

**Comment by averyocean65** [comment]
Oh, right. My apologies.
Well, I really appreciate that you took the time to answer my questions.

Have a great rest of your day!
