### ISSUE TITLE
[BUG] Broken with patch 15?? No setting for plugin config.

### ISSUE THREAD

**Issue by ghost** [eternalUnion/UKPluginConfigurator#9]
### Description
What went wrong, what should have happened
    When I launch the game, with no plugins except Plugin Configurator, or with all of my plugins, the "PLUGIN CONFIG" option in settings does not show.
### Reproduction
How to reproduce the bug (if the steps are known, else give as many information as possible which could help)
- Step 1: Launch the game with Plugin Configurator
- Step 2: Go to settings
- Step 3: No Plugin Config option.

### Installed plugins
- Plugin Configurator
- UltrakillStyleEditor
- V2PlasticChair
- FasterPunch
- BepInExPack
- Configgy
- StyleModifier
- I_WONt_SUGARCOAT_IT
- UltraModManager

### Extra
Anything you want to add
As I said previously, no matter what combination of mods I use, the Plugin Config option doesn't show. I used this mod just yesterday, prior to the patch, and it was working fine, that's what led me to the conclusion that something broke this with Patch 15.

**Comment by ghost** [comment]
Forgot to add the versions of the plugins i use. Also, there aren't any errors at all in the console log.

Plugin Configurator - v1.8.4
UltrakillStyleEditor - v1.0.4
V2PlasticChair - v2.0.2
FasterPunch - V1.0.5
BepInExPack - v5,4,2100
Configgy - v1.0.3
StyleModifier - v1.0.0
I_WONt_SUGARCOAT_IT - v2.0.0
UltraModManager - 5.6.0

**Comment by ghost** [comment]
oops (sorry)

**Comment by eternalUnion** [comment]
Update caused it and the problem is fixed in the code, but the new code is being tested. It will be released today.

**Comment by ghost** [comment]
Okay, thank you. Love the mod by the way :)
